# Generated by Django 5.2.5 on 2025-08-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_surveyresponse_delete_satisfactionsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='cc1',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='cc2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='cc3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='government',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('other_agency', 'Other Agency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
    ]
