# Generated by Django 5.2.5 on 2025-09-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(default='Client Satisfaction Measurement (CSM)', max_length=255)),
                ('intro_desc1', models.TextField(default='The Client Satisfaction Measurement (CSM) tracks the customer experience of government offices. Your feedback will help improve services.')),
                ('intro_desc2', models.TextField(default='Personal information shared will be kept confidential and optional.')),
                ('transaction_type', models.CharField(default='recently concluded transaction', max_length=255)),
                ('client_type_label', models.CharField(default='Client type:', max_length=255)),
                ('client_type_options', models.JSONField(default=list)),
                ('government_label', models.CharField(default='Government:', max_length=255)),
                ('government_options', models.JSONField(default=list)),
                ('visit_date_label', models.CharField(default='Date:', max_length=255)),
                ('sex_label', models.CharField(default='Sex:', max_length=255)),
                ('sex_options', models.JSONField(default=list)),
                ('age_label', models.CharField(default='Age:', max_length=255)),
                ('region_label', models.CharField(default='Region of Residence:', max_length=255)),
                ('office_person_label', models.CharField(default='Office Person Visited:', max_length=255)),
                ('service_availed_label', models.CharField(default='Service Availed:', max_length=255)),
                ('submit_text', models.CharField(default='NEXT', max_length=50)),
            ],
        ),
    ]
