# Generated by Django 5.2.5 on 2025-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_survey1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey1',
            name='client_type_options',
            field=models.JSONField(default=list, help_text='Example: ["Student Applicant", "Citizen (Student/Parents/Alumni)", "Business"]'),
        ),
        migrations.AlterField(
            model_name='survey1',
            name='government_options',
            field=models.JSONField(default=list, help_text='Example: ["Employee", "Other Agency"]'),
        ),
        migrations.AlterField(
            model_name='survey1',
            name='intro_desc1',
            field=models.TextField(default='The Client Satisfaction Measurement (CSM) tracks the customer experience of government offices. Your feedback on your recently concluded transaction will help this office provide a better service.'),
        ),
        migrations.AlterField(
            model_name='survey1',
            name='intro_desc2',
            field=models.TextField(default='Personal information shared will be kept confidential and you always have the option to not answer this form.'),
        ),
        migrations.AlterField(
            model_name='survey1',
            name='sex_options',
            field=models.JSONField(default=list, help_text='Example: ["Male", "Female", "Others"]'),
        ),
        migrations.AlterField(
            model_name='survey1',
            name='submit_text',
            field=models.CharField(default='NEXT', max_length=255),
        ),
    ]
