# Generated by Django 5.2.5 on 2025-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_alter_survey1_client_type_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(default="Please Check(✓) your answer to the Citizen's Charter (CC) questions. The Citizen's Charter is an official document that reflects the services of a government agency including its requirements, fees, and processing time among others.")),
                ('cc1_code', models.CharField(default='CC1', max_length=10)),
                ('cc1_question', models.TextField(default='Which of the following best describes your awareness of a CC?')),
                ('cc1_option1', models.CharField(default="I know what a CC is and I saw this office's CC.", max_length=255)),
                ('cc1_option2', models.CharField(default="I know what CC is but I did NOT see this office's CC.", max_length=255)),
                ('cc1_option3', models.CharField(default="I learned of the CC only when I saw this office's CC.", max_length=255)),
                ('cc1_option4', models.CharField(default="I do not know what a CC is and I did not see one in the office (Answer 'N/A' on CC2 and CC3)", max_length=255)),
                ('cc2_code', models.CharField(default='CC2', max_length=10)),
                ('cc2_question', models.TextField(default='If aware of the CC (answered 1-3 in CC1), would you say that the CC of this office was ...?')),
                ('cc2_option1', models.CharField(default='Easy to see', max_length=255)),
                ('cc2_option2', models.CharField(default='Somewhat easy to see', max_length=255)),
                ('cc2_option3', models.CharField(default='Difficult to see', max_length=255)),
                ('cc2_option4', models.CharField(default='Not visible at all', max_length=255)),
                ('cc2_option5', models.CharField(default='N/A', max_length=255)),
                ('cc3_code', models.CharField(default='CC3', max_length=10)),
                ('cc3_question', models.TextField(default='If aware of the CC (answered 1-3 in CC1), how much did the CC help you in your transaction?')),
                ('cc3_option1', models.CharField(default='Helped very much', max_length=255)),
                ('cc3_option2', models.CharField(default='Somewhat helped', max_length=255)),
                ('cc3_option3', models.CharField(default='Did not help', max_length=255)),
                ('cc3_option4', models.CharField(default='N/A', max_length=255)),
            ],
        ),
    ]
