# Generated by Django 5.2.5 on 2025-09-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_survey2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField(default='For SOD 0-8, please click the star (★) on the row that best corresponds to your answer.')),
                ('strongly_agree', models.CharField(default='Strongly Agree = ★★★★★', max_length=255)),
                ('agree', models.CharField(default='Agree = ★★★★', max_length=255)),
                ('neutral', models.CharField(default='Neither Agree nor Disagree = ★★★', max_length=255)),
                ('disagree', models.CharField(default='Disagree = ★★', max_length=255)),
                ('strongly_disagree', models.CharField(default='Strongly Disagree = ★', max_length=255)),
                ('not_applicable', models.CharField(default='N/A Not Applicable = Leave it blank', max_length=255)),
                ('feedback_label', models.CharField(default='Suggestion on how we can further improve our services (optional):', max_length=255)),
                ('email_label', models.CharField(default='Email address (Optional):', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Survey3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='playground.survey3')),
            ],
        ),
    ]
