# Generated by Django 5.2.5 on 2025-09-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_survey3_survey3question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey3question',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='survey3',
            old_name='instruction_text',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='disagree',
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='not_applicable',
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='strongly_agree',
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='strongly_disagree',
        ),
        migrations.AddField(
            model_name='survey3',
            name='instructions_stars',
            field=models.TextField(default='Strongly Agree = ★★★★★\nAgree = ★★★★\nNeither Agree nor Disagree = ★★★\nDisagree = ★★\nStrongly Disagree = ★\nN/A Not Applicable = Leave it blank'),
        ),
    ]
