# Generated by Django 5.2.5 on 2025-09-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_survey3question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey3question',
            options={},
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='survey3',
            name='instructions_stars',
        ),
        migrations.RemoveField(
            model_name='survey3question',
            name='order',
        ),
        migrations.AddField(
            model_name='survey3',
            name='instruction',
            field=models.TextField(default='For SOD 0-8, please click the star (★) on the row that best corresponds to your answer.'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='rating_table_header1',
            field=models.CharField(default='Service Quality Dimensions', max_length=255),
        ),
        migrations.AddField(
            model_name='survey3',
            name='rating_table_header2',
            field=models.CharField(default='Rating', max_length=255),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod0',
            field=models.TextField(default='I am satisfied with service that I availed'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod1',
            field=models.TextField(default='I spent a reasonable amount of time for my transaction.'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod2',
            field=models.TextField(default="The office followed the transaction's requirements and steps based on the information provided."),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod3',
            field=models.TextField(default='The steps (including payment) I needed to do my transaction were easy and simple.'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod4',
            field=models.TextField(default='I easily found information about my transaction from the office or its website.'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod5',
            field=models.TextField(default='I paid a reasonable amount of fees for my transaction. (If service is free, mark N/A column)'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod6',
            field=models.TextField(default="I feel the office was fair to everyone or 'walang palakasan' during my transaction."),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod7',
            field=models.TextField(default='I was treated courteously by the staff, and (if asked for help) the staff was helpful.'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='sod8',
            field=models.TextField(default='I got what I needed from the government office, or (if denied) denial of request was sufficiently explained to me.'),
        ),
        migrations.AddField(
            model_name='survey3',
            name='stars_agree',
            field=models.CharField(default='Agree = ★★★★', max_length=255),
        ),
        migrations.AddField(
            model_name='survey3',
            name='stars_disagree',
            field=models.CharField(default='Disagree = ★★', max_length=255),
        ),
        migrations.AddField(
            model_name='survey3',
            name='stars_na',
            field=models.CharField(default='N/A Not Applicable = Leave it blank', max_length=255),
        ),
        migrations.AddField(
            model_name='survey3',
            name='stars_neutral',
            field=models.CharField(default='Neither Agree nor Disagree = ★★★', max_length=255),
        ),
        migrations.AddField(
            model_name='survey3',
            name='stars_strongly_agree',
            field=models.CharField(default='Strongly Agree = ★★★★★', max_length=255),
        ),
        migrations.AddField(
            model_name='survey3',
            name='stars_strongly_disagree',
            field=models.CharField(default='Strongly Disagree = ★', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey3',
            name='feedback_label',
            field=models.TextField(default='Suggestion on how we can further improve our services (optional):'),
        ),
    ]
